path_classifiers:
  library:
    - utils/lit
    - libs/none/musl
  docs:
    - README.md
    - LICENSE.txt
    - CREDITS.txt
    - docs/*md
  test:
    - test/lit

extraction:
  cpp:
    prepare:
      packages:
        # Can't install liblld-4.0-dev here; it's not on the whitelist. Trick LGTM into installing it later during configure.
        - llvm-4.0-dev
        - llvm-4.0-tools
        - llvm-4.0
        - llvm-4.0-runtime
        - texlive-latex-recommended
    after_prepare:
      - sed -i '/llvm-3/d' /opt/work/autobuild/deptrace-db.txt
      - sed -i '/llvm-5/d' /opt/work/autobuild/deptrace-db.txt
      - sed -i '/llvm-6/d' /opt/work/autobuild/deptrace-db.txt
      
    configure:
      command:
        - cat /usr/lib/llvm-4.0/include/lld/Config/Version.h > /dev/null # triggers installation of liblld-4.0-dev for alld
        - mkdir -p _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release ..
